Repository GDSC-UM-Indonesia/nextjs_finalproject, pull requests merged in 2023-06, with the labels that each got.

#9 feat: Quiz System and Data Storing with Google Spreadsheet
  .env.example
  .gitignore
  .vscode/settings.json
  package-lock.json
  package.json
  quizzes/firebase.json
  src/pages/api/report.js
  src/pages/quiz.jsx
  src/pages/quiz/[slug].jsx
  src/pages/quiz/index.jsx
Labels: enhancement

#12 (+) blog page
  posts/2-test.md
  posts/3-test.md
  src/assets/hero-blog.png
  src/assets/logo_gdsc.svg
  src/components/Footer.jsx
  src/components/HeroBlog.jsx
  src/components/Navbar.jsx
  src/pages/_document.js
  src/pages/blog/index.jsx
  src/styles/globals.css
Labels: enhancement, type:ui, type:ux

#20 hotfix: make article card render in split components
  quizzes/firebase.json
  src/components/ArticleCard.jsx
  src/pages/_document.js
  src/pages/blog/index.jsx
  src/pages/quiz/index.jsx
  src/styles/globals.css
  tailwind.config.js
Labels: enhancement, type:ui

#24 Test for markdown and json
  src/tests/articledata.test.js
  src/tests/quizdata.test.js
Labels: enhancement

#28 test: dynamic component rendering abilities
  jest.config.js
  package-lock.json
  package.json
  src/components/ArticleCard.jsx
  src/components/CardName.jsx
  src/components/__test__/CardName.test.jsx
  src/components/__test__/articlecard.test.jsx
  src/tests/articledata.test.js
Labels: type-testing

#34 feat(ui): reworking and implement figma ui design
  src/assets/404.svg
  src/assets/maitenance.svg
  src/assets/partner_elektro.png
  src/assets/partner_formadiksi.png
  src/assets/partner_icn.png
  src/assets/struktur.png
  src/components/404.jsx
  src/components/ArticleCard.jsx
  src/components/CardName.jsx
  src/components/Maitenance.jsx
  src/components/Navbar.jsx
  src/pages/404.js
  src/pages/_document.js
  src/pages/blog/[slug].jsx
  src/pages/blog/index.jsx
  src/pages/index.jsx
  src/pages/partner.jsx
  src/pages/profile.jsx
  src/pages/quiz/index.jsx
  src/pages/team.jsx
Labels: type-feature, scope-ui, scope-ux

#41 ci: lighthouse and node matrix test
  .github/lighthouserc-prod.json
  .github/lighthouserc.json
  .github/workflows/lighthouse-prod.yml
  .github/workflows/lighthouseci.yml
  .github/workflows/tests.yml
  .github/workflows/upgrade-compability.yml
  package-lock.json
  package.json
Labels: type-testing, scope-dx, scope-ci/cd
